- name: Install the semaphore Application
  hosts: semaphore
  become: true
  gather_facts: false
  vars:
    golang_version: '1.22.1'
    golang_install_dir: "/opt/go/{{ golang_version }}"
    golang_gopath: "{{ golang_install_dir }}"
    semaphore_dir: "{{ golang_gopath }}/src/github.com/tobychui/semaphore"  
  pre_tasks:

    - name: Create semaphore group
      ansible.builtin.group:
        name: semaphore
        state: present
        system: true

    - name: Create semaphore service user
      ansible.builtin.user:
        name: semaphore
        system: true
        password_lock: true
        state: present
        group: semaphore

    - name: Download the semaphore application
      ansible.builtin.get_url:
        url: https://github.com/semaphoreui/semaphore/releases/download/v2.9.64/semaphore_2.9.64_linux_amd64.tar.gz
        dest: /tmp
        mode: "0755"

    - name: Unpack the semaphore application
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/semaphore_2.9.64_linux_amd64.tar.gz
        dest: /usr/bin

    - name: Set semaphore bin to dedicated account
      ansible.builtin.file:
        path: /usr/bin/semaphore
        state: file
        owner: semaphore
        group: semaphore
        mode: "0700"
    
    - name: Create the etc/semaphore directory
      become: true
      ansible.builtin.file:
        path: /etc/semaphore
        mode: "0700"
        owner: semaphore
        group: semaphore
        recurse: true
        state: directory

    - name: Create the var/lib/semaphore directory
      become: true
      ansible.builtin.file:
        path: /var/lib/semaphore
        mode: "0700"
        owner: semaphore
        group: semaphore
        recurse: true
        state: directory

    - name: Create the tmp/semaphore directory
      become: true
      ansible.builtin.file:
        path: /tmp/semaphore
        mode: "0740"
        owner: semaphore
        group: semaphore
        recurse: true
        state: directory

    - name: Create the semaphore config
      become: true
      ansible.builtin.copy:
        content: |
          {
            "bolt": {
              "host": "/var/lib/semaphore/semaphore.bolt",
            },
            "dialect": "bolt",
            "access_key_encryption": "{{ semaphore_access_token }}",
            "cookie_hash": "{{ semaphore_cookie_token }}",
            "web_host": "{{ semaphore_endpoint }}"
          }
        dest: /etc/semaphore/config.json
        mode: "0600"
        owner: semaphore
        group: semaphore

  roles:
    - name: cimon-io.systemd-service
      become: true
      vars:
        systemd_service:
          semaphore:
            enabled: false
            description: "Ansible Semaphore"
            exec_start: "/usr/bin/semaphore server --config /etc/semaphore/config.json"
            exec_reload: "/bin/kill -HUP $MAINPID"
            user: semaphore
            group: semaphore
            restart: "always"
            restart_sec: "10"
            wants: "network-online.target"
            after: "network-online.target"

            wanted_by: "multi-user.target"

  post_tasks:

    - name: Start the systemd service for semaphore
      become: true
      ansible.builtin.systemd_service:
        name: semaphore
        state: started
        enabled: true

    - name: Create the admin account
      become: true
      become_user: semaphore
      ansible.builtin.shell:
        cmd: |
          semaphore user add --admin --login {{ semaphore_admin }} \
            --name {{ semaphore_admin }} --email {{ semaphore_email }} --password {{ semaphore_token }} \
            --config /etc/semaphore/config.json

        
