- name: Install Technitium
  hosts: technitiumdns
  remote_user: "{{ ansible.user }}"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Download install script
      ansible.builtin.get_url:
        url: https://download.technitium.com/dns/install.sh
        dest: /tmp/technitium_install.sh
        mode: "0700"
  tasks:
    # the same script is used to both install and update the server package
    - name: Install Technitium from Script
      ansible.builtin.script: /tmp/technitium_install.sh
