---
# tasks file for technohouser.proxmox_create_lxc
# TODO: add pre-generated host keys and ansible account keys to the bootstrap image

- name: Remove host keys from known hosts for controller 
  ansible.builtin.known_hosts:
    name: "{{ pve_hostname }}"
    state: absent

- name: Remove fqdn host keys from known hosts for controller
  ansible.builtin.known_hosts:
    name: "{{ pve_hostname }}.{{ domain.alt }}"
    state: absent

- name: Add LXC container template to node
  community.general.proxmox_template:
    node: "{{ pve_node }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    template: "{{ pve_lxc_ostemplate_name | default(omit) }}"
    src: "{{ pve_lxc_ostemplate_src if(pve_lxc_ostemplate_src is defined) else ( pve_lxc_ostemplate_downloaded.dest if(pve_lxc_ostemplate_downloaded.dest is defined) ) | default(omit) }}"
    storage: "{{ pve_lxc_ostemplate_storage | default(omit) }}"
    content_type: "{{ pve_lxc_ostemplate_content_type | default(omit) }}"
    timeout: "{{ pve_lxc_ostemplate_timeout | default(omit) }}"
    force: "{{ pve_lxc_ostemplate_force | default(omit) }}"
    validate_certs: "{{ pve_validate_certs | default(omit) }}"
    state: "{{ pve_lxc_ostemplate_state  | default(omit) }}"
  tags:
    - pve_descarga
    - pve_download

# TODO: permit api_token_id: api_token_secret: only if features are not being modified that require root@pam
# TODO: Add ethernet adapter
- name: Create the container
  community.general.proxmox:
    node: "{{ pve_node }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    validate_certs: "{{ pve_validate_certs | default(omit) }}"
    hookscript: "{{ pve_lxc_hookscript | default(omit) }}"
    ostemplate: "{{ pve_lxc_ostemplate_storage | default('local') }}:{{ pve_lxc_ostemplate_content_type | default('vztmpl') }}/{{ pve_lxc_ostemplate_name if(pve_lxc_ostemplate_name is defined) else ( pve_lxc_ostemplate_url | urlsplit('path') | basename ) }}"
    hostname: "{{ pve_hostname }}"
    pubkey: "{{ pve_lxc_root_authorized_pubkey | default(omit) }}"
    cores: "{{ pve_lxc_cpu_cores | default(omit) }}"
    cpus: "{{ pve_lxc_cpu_limit | default(omit) }}"
    memory: "{{ pve_lxc_memory | default(omit) }}"
    disk: "{{ pve_lxc_disk | default(omit) }}"
    swap: "{{ pve_lxc_swap | default(omit) }}"
    storage: "{{ pve_lxc_storage | default(omit) }}"
    vmid: "{{ pve_lxc_vmid | default(omit) }}"
    description: "{{ pve_lxc_description | default(omit) }}"
    password: "{{ pve_lxc_root_password }}"
    mounts: >-
      {   {%- for item in pve_lxc_mounts -%}
            "{{ item.id }}":"{{ item.storage|default('local-lvm') }}:{{ item.size|default(32) }},mp={{ item.mount_point|default('/mnt/mp0') }},{% if item.acl is defined %}{% if (item.acl) %}acl=1{% else %}acl=0{% endif %},{% endif %}{% if item.quota is defined and item.quota %}quota=1,{% endif %}{% if item.read_only is defined and item.read_only %}ro=1,{% endif %}{% if item.backup is defined and item.backup %}backup=1,{% endif %}{% if item.skip_replication is defined and item.skip_replication %}replicate=0{% endif %}",
          {%- endfor -%}  }
    netif: >-
      {   {%- for item in pve_lxc_net_interfaces -%}
            "{{ item.id }}":"name={{ item.name }},bridge={{ item.bridge }},{% if (item.hwaddr is defined) %}hwaddr={{ item.hwaddr }},{% endif %}{% if (item.ip4 is defined) %}ip={{ item.ip4 }}/{{ item.netmask4 }},{% endif %}{% if (item.gw4 is defined) %}gw={{ item.gw4 }},{% endif %}{% if (item.ip6 is defined) %}ip6={{ item.ip6 }}/{{ item.netmask6 }},{% endif %}{% if (item.gw6 is defined) %}gw6={{ item.gw6 }},{% endif %}{% if (item.firewall is defined and item.firewall) %}firewall=1,{% endif %}{% if (item.rate_limit is defined) %}rate={{ item.rate_limit }},{% endif %}{% if (item.vlan_tag is defined) %}tag={{ item.vlan_tag }}{% endif %}",
          {%- endfor -%}  } 
    nameserver: "{{ pve_lxc_nameserver | default(omit) }}"
    searchdomain: "{{ pve_lxc_searchdomain | default(omit) }}"
    onboot: "{{ pve_onboot | default(omit) }}"
    unprivileged: "{{ pve_lxc_unprivileged | default(omit) }}"
    features: "{{ pve_lxc_features | default(omit) }}"
    timeout: "{{ pve_lxc_timeout | default(omit) }}"
    state: present
  register: pve_lxc_container_created
  notify:
    - Start the container
    - Wait for connection
