# defaults file for /home/ansible@hettenhouser.com/.local/share/dasbootstrap/ansible/roles/technohouser.ansible-create-lxc
ansible:
  user: ansible
  user_home: ansible
  user_shell: /bin/zsh
  password: I1cannot2simply3write4p@ssw0rd!
  home: "{{ lookup('env', 'HOME') }}/.ansible"

# nfs mount directory for qemu images and lxc archives
template_home: /mnt/pve/templates
ansible_home: "{{ lookup('env', 'HOME') }}/.ansible"

# lxc templates for various operating systems.
os_template:
  debian: "{{ template_home }}/template/cache/debian-12-standard_12.2-1_amd64.tar.zst"
  ubuntu: "{{ template_home }}/template/cache/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"

github_repos_master:
  - https://github.com/borland502/Proxmox-Automation.git
  - https://github.com/tteck/Proxmox.git

github_repos_main:
  - https://github.com/borland502/dasbootstrap

systemd_sleep:
  allow_suspend: false
  allow_hibernation: false
  allow_suspend_then_hibernate: false
  allow_hybrid_sleep: false

# https://github.com/bodsch/ansible-collection-systemd/blob/main/roles/resolved/defaults/main.yml
systemd_resolved:
  dns:
    - 1.1.1.1
    - 8.8.8.8

# https://github.com/bodsch/ansible-collection-systemd/blob/main/roles/timesyncd/defaults/main.yml
systemd_timesyncd:
  ntp:
    - 0.us.pool.ntp.org
    - 1.us.pool.ntp.org
    - 2.us.pool.ntp.org
    - 3.us.pool.ntp.org
  fallback_ntp:
    - time-a-g.nist.gov
    - time-b-g.nist.gov
    - time-c-g.nist.gov
    - time-d-g.nist.gov
    - time-e-g.nist.gov

package_list:
  - name: zsh
  - name: systemd
  - name: systemd-cron
  - name: systemd-resolved
  - name: systemd-timesyncd
  - name: vim
  - name: git
  - name: curl
  - name: p7zip-full
  - name: packagekit
  - name: rsync
  - name: apt-transport-https
  - name: fonts-firacode
