---
# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
        types: [python]
      - id: forbid-submodules
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
        args: [--py312]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py312]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        name: check poetry files
        entry: poetry check
        language: system
        pass_filenames: false
      - id: poetry-lock
        name: check poetry lock
        entry: poetry lock
        language: system
        pass_filenames: false
      - id: poetry-export
        name: export poetry
        entry: poetry export
        language: system
        pass_filenames: false
      - id: poetry-install
        name: install poetry
        entry: poetry install
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        types: [yaml]
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types_or: [python, pyi]
        args: [-iii, -ll]
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types_or: [python, pyi]
        args: [--py312]
