---
- name: Increase file limit for systemd
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^#DefaultLimitNOFILE=$"
    line: "DefaultLimitNOFILE=4096:524288"

- name: Increase file limit for systemd
  ansible.builtin.lineinfile:
    path: /etc/systemd/user.conf
    regexp: "^#DefaultLimitNOFILE=$"
    line: "DefaultLimitNOFILE=4096:524288"

- name: Increase UDP read buffer to 25MB
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: 2500000
    state: present
  when: ansible_virtualization_type != 'lxc'

- name: Increase UDP write buffer to 25MB
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: 2500000
    state: present
  when: ansible_virtualization_type != 'lxc'

  # https://github.com/woanware/ansible/blob/master/work.yml
- name: Tell the kernel to only swap if it really needs it
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 1
    state: present
  when: ansible_virtualization_type != 'lxc'

- name: Append line to .zshenv if not present so that brew is available to interactive and non-interactive sessions
  ansible.builtin.lineinfile:
    path: $HOME/.zshenv
    line: "eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    mode: "0644"
    create: true
    state: present
- name: Add service account to passwordless sudo
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ ansible.domain_user }}"
    line: "{{ ansible.domain_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"
    mode: "0644"
