---
- name: Wait for connection
  ansible.builtin.wait_for_connection:
    connect_timeout: 5
    delay: 10
    sleep: 5
    timeout: 120

- name: Enable passwordless sudo for the ansible_user
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ ansible.user }}"
    line: "{{ ansible.user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: "visudo -cf %s"
    mode: "0444"

- name: Set shell for user
  become: true
  ansible.builtin.user:
    name: "{{ ansible.user }}"
    shell: /bin/zsh
    comment: "Service User"

- name: Set linux brew directory to service user
  become: true
  ansible.builtin.file:
    path: "/home/linuxbrew"
    mode: "0775"
    owner: "{{ ansible.user }}"
    group: "{{ ansible.user }}"
    state: directory
    recurse: true

# Variable expected by this role will collide with a role used to bootstrap users, so define here
- name: Install homebrew
  ansible.builtin.import_role:
    name: professormanhattan.homebrew
  vars:
    # noqa: var-naming[no-role-prefix]
    user:
      username: "{{ ansible.user }}"

- name: Install some common service / user brew packages
  community.general.homebrew:
    name:
      - zsh
      - gcc
      - git
      - vim
      - fzf
      - bat
      - zinit
      - chezmoi
      - starship
      - pyenv
      - fzf
      - rg
      - fd
      - eza
      - prettyping
      - nmap
      - rsync

- name: Make ~/bin
  become: true
  ansible.builtin.file:
    state: directory
    path: "/home/{{ ansible.user }}/bin"
    mode: "0750"
    owner: "{{ ansible.user }}"
    group: "{{ ansible.user }}"

- name: Copy the age key over to ~/bin
  become: true
  ansible.builtin.copy:
    content: "{{ users[0]['age_key'] }}"
    dest: "/home/{{ ansible.user }}/bin/key.txt"
    mode: "0600"
    owner: "{{ ansible.user }}"
    group: "{{ ansible.user }}"

- name: Initialize the chezmoi repo and apply the configuration
  ansible.builtin.import_role:
    name: hussainweb.chezmoi

- name: Disable root login by passwd
  become: true
  ansible.builtin.user:
    name: root
    password_lock: true

- name: Switch service account to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible.user }}"
    shell: "/home/linuxbrew/.linuxbrew/bin/zsh"
  when: ansible_facts['user_shell'] != '/home/linuxbrew/.linuxbrew/bin/zsh'
