pve_hostname: "example"
pve_lxc_searchdomain: example.com # Optional.
pve_lxc_vmid: 2300
pve_lxc_net_interfaces:
  - id: net0
    name: eth0
    ip4: 10.10.10.10
    netmask4: 24
    gw4: 10.10.10.1
    bridge: vmbr0
    firewall: false

dns:
  record: "example"
  value: 10.10.10.10
