---
collections:
  - name: "ansible.posix"
    version: "*"

  - name: "community.general"
    version: "*"

  - name: "microsoft.ad"
    version: "*"

  - name: "community.docker"
    version: "*"

  - name: "robertdebock.roles"
    version: "*"

  - name: "buluma.roles"
    version: "*"

  - name: "debops.debops"
    version: "*"

  - name: "linuxhq.linux"
    version: "*"

  - name: "linuxhq.cloudflare"
    version: "*"

  - name: git+https://github.com/borland502/proxmox-ansible.git
    type: git
    version: "*"
# ansible-galaxy collection install cloudcodger.proxmox_openssh
# ansible-galaxy collection install nightly_brew.ansible_guacamole
# ansible-galaxy collection install hasnimehdi91.keepass
# https://galaxy.ansible.com/ui/repo/published/arensb/truenas/docs/
