---

# <https://github.com/MrMarble/home-ops/blob/315a54f0a93cb8e0ff2b1900f1f80373e3cb905d/.github/linters/.markdownlint.yaml>

default: true

# MD013/line-length - Line length

MD013:

# Number of characters

  line_length: 240

# Number of characters for headings

  heading_line_length: 80

# Number of characters for code blocks

  code_block_line_length: 80

# Include code blocks

  code_blocks: true

# Include tables

  tables: true

# Include headings

  headings: true

# Include headings

  headers: true

# Strict length checking

  strict: false

# Stern length checking

  stern: false
