---
# TODO: Framework level prep (check out other metaprojects like bootware, support scripts, personal scripts, etc)

# TODO: Remove existing key for bootstrap image in known hosts
# ssh-keygen -f "/home/ansible@hettenhouser.com/.ssh/known_hosts" -R "bootstrap.local.technohouser.com"

- name: Create LXC Base Image
  hosts: "localhost"
  ignore_unreachable: true
  gather_facts: false
  remote_user: root
  environment:
    PATH: /usr/local/bin:/usr/bin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/opt/python/bin:/home/linuxbrew/.linuxbrew/lib/python3.11/site-packages  
  vars_files:
    - /etc/ansible/global_vars/all.yaml
    - /etc/ansible/global_vars/pve.yaml
  pre_tasks:
    # TODO: Preflight check
  roles:
    - role: proxmox_create_lxc

- name: Update LXC Base Image
  hosts: "{{ pve_hostname }}"
  ignore_unreachable: false
  gather_facts: true
  remote_user: root
  become: true
  environment:
    PATH: /usr/local/bin:/usr/bin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/opt/python/bin:/home/linuxbrew/.linuxbrew/lib/python3.11/site-packages  
  vars_files:
    - /etc/ansible/global_vars/pve.yaml
    - /etc/ansible/global_vars/all.yaml
  roles:
    - role: scruffaluff.bootware.age
    - role: scruffaluff.bootware.git
    - role: buluma.locale
    - role: buluma.auto_update
      vars:
        auto_update_apply_updates: true
    - role: buluma.sudo
    - role: buluma.timezone
      vars:
        timezone: "America/New_York"
    - role: buluma.vim
    # # - role: buluma.hosts
    # #   delegate_to: "localhost"
    #   vars:
    #     hosts_inventory_to_hosts: true
    - role: GROG.package
      vars:
        package_state: latest
        package_update_cache: true
        package_list:
          - name: zsh
          - name: curl
          - name: realmd
          - name: sssd-tools
          - name: sssd
          - name: libnss-sss
          - name: libpam-sss
          - name: adcli
          - name: packagekit
    - role: update_lxc

# TODO: system level changes (sysctl, systemd, apt, etc)

# TODO: ansible domain user changes (homebrew, join domain, etc)

# TODO: Trigger app install(s) (Jenkins, Nexus, etc)
    
