---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  remote_user: root
  vars_files:
    - /etc/ansible/global_vars/all.yaml
    - /etc/ansible/global_vars/pve.yaml
  roles:
    - name: destroy_lxc
  tasks:
    # Developer must implement.

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler
