---
# Configuration for a DebOps project

project:
  default_view: 'system'

  git:

    # Automatically commit changes when certain actions are performed, for
    # example unlocking or locking the project directory
    auto_commit: True
    auto_commit_message: 'Changes committed automatically by DebOps'

# Define custom paths which can be used to override files and templates in
# Ansible roles or inject tasks via lookup plugins provided with DebOps.
# THe paths are relative to the project root directory.
override_paths:
  files_path: 'ansible/overrides/files'
  tasks_path: 'ansible/overrides/tasks'
  templates_path: 'ansible/overrides/templates'
