---
- name: Setup basic environment
  hosts: automation
  remote_user: ansible
  gather_facts: true
  vars_files:
    - "{{ lookup('env','HOME') }}/.ansible/inventory/group_vars/all.yaml"
    - "{{ lookup('env','HOME') }}/.ansible/inventory/host_vars/automation.yaml"
  roles:
    - role: technohouser.dasbootstrap.bootstrap
      become: true
    - role: technohouser.dasbootstrap.ansible
