---
- name: Import Debian LXC boostrap playbook
  ansible.builtin.import_playbook: playbooks/debian_lxc_bootstrap.yaml

- name: Import Debina kvm playbook
  ansible.builtin.import_playbook: playbooks/debian_kvm_bootstrap.yaml
