- name: Import Debian boostrap playbook
  ansible.builtin.import_playbook: playbooks/debian_lxc_bootstrap.yaml

# - name: Import Jenkins bootstrap playbook
#   ansible.builtin.import_playbook: playbooks/jenkins.yaml
