---
# tasks file for /home/ansible@hettenhouser.com/.local/share/dasbootstrap/ansible/roles/technohouser.ansible-create-lxc
- name: Get home directory
  set_fact:
    home_dir: "{{ lookup('env', 'HOME') }}"

# tasks file for /home/ansible@hettenhouser.com/.local/share/dasbootstrap/ansible/roles/technohouser.ansible-bootstrap
- name: Create Development Directory for Repos
  ansible.builtin.file:
    path: "{{ home_dir }}/Development/github"
    state: directory
    mode: 0700
    owner: ansible
    group: ansible

- name: Looping over github_repos var, clone each entry
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: /opt/{{ item.split('/')[-1].replace('.git', '') }} # extract repo name
    update: no
  loop: "{{ github_repos }}"
